modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" 

[[mods]] 

modId="folklorearcana" 

version="1.0" 

displayName="Folklore Arcana" 


updateJSONURL="http://myurl.me/" 

displayURL="http://example.com" 

logoFile="examplemod.png" 

credits="MindFlexibility"


authors="MindFlexibility" 


description='''
	This is a description and I don't know what to write here!
'''






[[dependencies.folklorearcana]] 
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
    

[[dependencies.folklorearcana]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
